Added test for refuses to be written, added a var for new_message.
Failures:

  1) SecretDiary when locked refuses to be written
     Failure/Error: expect(new_diary.write(new_message)).to eq "Go away!"

     NameError:
       undefined local variable or method `new_message' for #<RSpec::ExampleGroups::SecretDiary::WhenLocked:0x00007f9d201eeb18>
     # ./spec/secret_diary_spec.rb:29:in `block (3 levels) in <top (required)>'

Finished in 0.00265 seconds (files took 0.0853 seconds to load)
4 examples, 1 failure, 2 pending

Failed examples:

rspec ./spec/secret_diary_spec.rb:28 # SecretDiary when locked refuses to be written

➜  testing_relationships_between_classes git:(master) ✗ rspec
..**

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) SecretDiary when unlocked gets read
     # Not yet implemented
     # ./spec/secret_diary_spec.rb:35

  2) SecretDiary when unlocked gets written
     # Not yet implemented
     # ./spec/secret_diary_spec.rb:37

Finished in 0.00361 seconds (files took 0.07844 seconds to load)
4 examples, 0 failures, 2 pending